### PR TITLE
skip test modules with tarpaulin

### PR DESCRIPTION
**Pull request by msarahan**
I'm not sure why test coverage went down for a change I made in the
tests.  I see that tarpaulin isn't in use yet, but perhaps when it is,
this might help with misleading coverage info.

Edit: this attempt is based on info at https://github.com/xd009642/tarpaulin#ignoring-code-in-files

### CODE REVIEW

**Comment by timvisee** [comment]
Could you elaborate what this change is for? Does this prevent tracking coverage status for the unit tests (in this case)?

Not sure why coverage dropped either. It seems to be a bit flaky, so don't worry too much about the percentage value.

**Comment by msarahan** [comment]
The intent is that the tests themselves are not considered in the coverage count.  The coverage number should only apply to the library code, and the tests are the code that exercise the library code, but the lines in the tests themselves should not count towards any coverage number.

I may be way off-base here since I'm so new to rust.  The pattern of incorporating unit tests in the same file as the code is a bit foreign to me.  I like it, but it makes me suspicious of things like coverage here.  Is coverage treating the test module as code that is covered (or not)?

**Comment by timvisee** [comment]
> The intent is that the tests themselves are not considered in the coverage count. The coverage number should only apply to the library code, and the tests are the code that exercise the library code, but the lines in the tests themselves should not count towards any coverage number.
> 
> I may be way off-base here since I'm so new to rust. The pattern of incorporating unit tests in the same file as the code is a bit foreign to me. I like it, but it makes me suspicious of things like coverage here. Is coverage treating the test module as code that is covered (or not)?

Yes, perfect. It appears that the current coverage tester does include the unit tests, judging by:
https://coveralls.io/builds/26000307/source?filename=version.rs#L465

I'm not sure what tarpaulin would do with these right now, but it definitely won't be bad to include this anyway.

**Comment by timvisee** [comment]
I updated your [`tarpaulin`](https://github.com/msarahan/version-compare/commits/tarpaulin) branch to include this change for all (new) test modules. I hope that's alright.

Will merge now.

**Comment by msarahan** [comment]
Sure! I hope this helps.

**Pull request merged**
