### PR TITLE
Show failing assertion case in comparisons

### PR DESCRIPTION
**Pull request by msarahan**
The collection approach is great for reuse of the test cases, but
obfuscates which test case is failing.  Hopefully this helps show
which case needs examination.

Signed-off-by: Michael Sarahan <msarahan@gmail.com>

### CODE REVIEW

**Comment by timvisee** [comment]
Brilliant! Thanks for this, will merge soon.

**Comment by msarahan** [comment]
@timvisee some context here: I want to use your library here as the basis for porting parts of conda (https://github.com/conda/conda) which is currently in Python into Rust.  Conda has its own rather particular version behavior, primarily defined by Python: https://github.com/conda/conda/blob/master/conda/models/version.py

Your library is a great start, but I'm having to modify it for the special behavior defined in that file.  Specifically:

1. we use lexicographical sorting for alphabetical version components
2. we special-case "dev" and "post" versions
3. we support epochs with the ! syntax

If you're interested in having these in your library, I'll put up PR's for discussion.  Otherwise, if you have suggestions for how to extend your library locally, I'd appreciate it.  I'm a complete rust newbie.

**Comment by timvisee** [comment]
> @timvisee some context here: I want to use your library here as the basis for porting parts of conda (https://github.com/conda/conda) which is currently in Python into Rust. Conda has its own rather particular version behavior, primarily defined by Python: https://github.com/conda/conda/blob/master/conda/models/version.py
> 
> Your library is a great start, but I'm having to modify it for the special behavior defined in that file. Specifically:
> 
>     1. we use lexicographical sorting for alphabetical version components
> 
>     2. we special-case "dev" and "post" versions
> 
>     3. we support epochs with the ! syntax
> 
> 
> If you're interested in having these in your library, I'll put up PR's for discussion. Otherwise, if you have suggestions for how to extend your library locally, I'd appreciate it. I'm a complete rust newbie.

That sounds great!

I do want to give this library a full rewrite, with a better modular design while providing a similar API interface. With this redesign I'd like to support all version formats thinkable, with optional extensibility by crate users for special cases. I didn't have the time for this though, nor have I been able to think of a design yet. Some users made cool suggestions but it has not been concretized yet.

Therefore I think I must suggest to implement these version specific changes in your own fork first, until a good redesign is made for this crate. Though, if you think you'll be able to implement the changes to desire without breaking current version comparisons I'm open for that as well.

If using your own fork, you might be interested in [this](https://github.com/timvisee/version-compare/issues/15#issuecomment-509358927) design suggestion, as I'll probably move into that direction with this crate.

Here's an issue on the redesign idea, though there isn't much described here yet: https://github.com/timvisee/version-compare/issues/13

**Comment by msarahan** [comment]
> With this redesign I'd like to support all version formats thinkable, with optional extensibility by crate users for special cases. I didn't have the time for this though, nor have I been able to think of a design yet. Some users made cool suggestions but it has not been concretized yet.

My thought so far has been to make splitting the string customizable using a vector of splitting specs in the VersionManifest.  That will get me a bit further, but I think https://github.com/timvisee/version-compare/issues/15#issuecomment-509358927 would be necessary for resolving any differences in comparison behavior between ecosystems.  Thanks for the reference.  If I come up with something that feels nice, I'll see if you like the design enough to adopt it here.

**Comment by timvisee** [comment]
> My thought so far has been to make splitting the string customizable using a vector of splitting specs in the VersionManifest.

That is probably one of the things to do indeed. I've thought about a design before (briefly) and it appears to be quite hard to think of something that is generic and reusable across different version schemes.

String splitting into parts must be customizable. There could be an arbitrary number of part types. Comparison between parts could be varying a lot. There might be a need to compare parts of different types. Some parts have special cases. Version strings might not be little-endian. And so on...

I might be able to document all requirements and desired features into a design issue in the upcoming week, by looking some version schemes that are publicly used such as semver and the scheme Anaconda uses. After that it will be easier to think of and settle on to an architectural design.

**Pull request merged**
