### PR TITLE
implemented text part comparision

### PR DESCRIPTION
**Pull request by evilsocket**
This pull requests introduces best-effort version text part comparision. Before this PR, `1.0.0 RC1` was considered equal to `1.0.0 RC2`, same goes for `1.0.0 alpha` and `1.0.0 beta` or similar. This patch fixes that.

### CODE REVIEW

**Review by timvisee — APPROVED** [review]

**Comment by timvisee** [comment]
Very useful. Thanks a lot!

**Comment by evilsocket** [comment]
My pleasure! Do you have any ETA for tagging a new version that'll include this fix? I'm using this crate in a project and referencing a version is much cleaner than referencing a repo :)

**Comment by evilsocket** [comment]
you tha best

**Comment by timvisee** [comment]
Published this as part of `v0.0.13` just now!

**Pull request merged**
